spring:
  application:
    name: demo
    
management:
  endpoints:
    web:
      exposure:
        include: '*'

resilience4j.bulkhead:
  configs:
    default:
      max-concurrent-calls: 5
      max-wait-duration: 0
  instances:
    ApsBackendService:
      baseConfig: default
    LexisNexisBackendService:
      baseConfig: default

resilience4j.timelimiter:
  configs:
    default:
      cancelRunningFuture: true
      timeoutDuration: 2000ms
  instances:
    EcprBackendService:
      baseConfig: default
    LexisNexisBackendService:
      baseConfig: default

resilience4j.ratelimiter:
  configs:
    default:
      limit-for-period: 4
      limit-refresh-period: 1s
      timeout-duration: 0s
      allow-health-indicator-to-fail: true
      subscribe-for-events: true
      event-consumer-buffer-size: 50
  instances:
    EwsBackendService:
      baseConfig: default
    #LexisNexisBackendService:
      #baseConfig: default

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 60
      minimumNumberOfCalls: 60
      permittedNumberOfCallsInHalfOpenState: 20
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 60s
      failureRateThreshold: 50
      eventConsumerBufferSize: 50
      slowCallDurationThreshold: 1900
  instances:
    SimsBackendService:
      baseConfig: default
    LexisNexisBackendService:
      baseConfig: default    

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 100
      retry-exceptions:
        - java.lang.Exception        
  instances:
    AngBackendService:
      baseConfig: default
    #LexisNexisBackendService:
      #baseConfig: default      

backendService:
  baseUrl:  http://localhost:9090  
  path:
    aps:  /api/aps    
    ecpr: /api/ecpr
    ews:  /api/ews
    sims: /api/sims
    ang:  /api/ang
    lexisNexis: /api/lexisNexis
    
#apsUrl: http://localhost:9090/api/aps
apsUrl: https://az-tmpe-cav-dcg-t06.wellsfargo.com:8443/api/aps
ecprUrl: https://az-tmpe-cav-dcg-t06.wellsfargo.com:8443/api/ecpr
ewsUrl: https://az-tmpe-cav-dcg-t06.wellsfargo.com:8443/api/ews
simsUrl: https://az-tmpe-cav-dcg-t06.wellsfargo.com:8443/api/sims
angUrl: https://az-tmpe-cav-dcg-t06.wellsfargo.com:8443/api/ang
lexisNexisUrl: https://az-tmpe-cav-dcg-t06.wellsfargo.com:8443/api/lexisNexis

CAV_APP_AGENT_TIER: resilience4jDemoOcp
CAV_APP_AGENT_NDCPORT: 443
CAV_APP_AGENT_NDCHOST: az-tmpe-cav-dcg-t06.wellsfargo.com
CAV_APP_AGENT_NDC_COMM_PROTOCOL: TCP




server:
  tomcat:
    accesslog:
      directory: /dev
      enabled: true
      prefix: stdout
      buffered: false
      suffix: ""
      file-date-format: ""

logging:
  level:
    root: INFO
    io:
      github: INFO
    okhttp3:  INFO
    com:
      demo: INFO   
      