spring:
  boot:
    admin:
      client:
        url: http://localhost:8080
  application:
    name: demo
        
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  security:
    enabled: false

resilience4j.bulkhead:
  configs:
    default:
      max-concurrent-calls: 5
      max-wait-duration: 0
  instances:
    Ip1BackendService:
      baseConfig: default
    Ip6BackendService:
      baseConfig: default

resilience4j.timelimiter:
  configs:
    default:
      cancelRunningFuture: true
      timeoutDuration: 2000ms
  instances:
    Ip2BackendService:
      baseConfig: default
    Ip6BackendService:
      baseConfig: default

resilience4j.ratelimiter:
  configs:
    default:
      limit-for-period: 4
      limit-refresh-period: 1s
      timeout-duration: 0s
      allow-health-indicator-to-fail: true
      subscribe-for-events: true
      event-consumer-buffer-size: 50
  instances:
    Ip3BackendService:
      baseConfig: default
    #Ip6BackendService:
      #baseConfig: default

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 360
      minimumNumberOfCalls: 360
      permittedNumberOfCallsInHalfOpenState: 60
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 60s
      failureRateThreshold: 80
      eventConsumerBufferSize: 80
      slowCallDurationThreshold: 2200
  instances:
    Ip4BackendService:
      baseConfig: default
    Ip6BackendService:
      baseConfig: default    

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 100
      retry-exceptions:
        - java.lang.Exception        
  instances:
    Ip5BackendService:
      baseConfig: default
    #Ip6BackendService:
      #baseConfig: default      

backendService:
  baseUrl:  http://localhost:9090  
  path:
    iP1:  /api/ip1    
    iP2: /api/ip2
    iP3:  /api/ip3
    iP4: /api/ip4
    iP5:  /api/ip5
    iP6: /api/ip6
    
iP1Url: http://localhost:9090/api/ip1
iP2Url: http://localhost:9090/api/ip2
iP3Url: http://localhost:9090/api/ip3
iP4Url: http://localhost:9090/api/ip4
iP5Url: http://localhost:9090/api/ip5
iP6Url: http://localhost:9090/api/ip6


server:
  tomcat:
    accesslog:
      directory: /dev
      enabled: true
      prefix: stdout
      buffered: false
      suffix: ""
      file-date-format: ""

logging:
  level:
    root: INFO
    io:
      github: INFO
    okhttp3:  INFO
    com:
      demo: INFO   