spring:
  application:
    name: demo
    
management:
  endpoints:
    web:
      exposure:
        include: '*'

resilience4j.bulkhead:
  configs:
    default:
      max-concurrent-calls: 2
      max-wait-duration: 0
  instances:
    ApsBackendService:
      baseConfig: default
    LexisNexisBackendService:
      baseConfig: default

resilience4j.timelimiter:
  configs:
    default:
      cancelRunningFuture: true
      timeoutDuration: 1500ms
  instances:
    EcprBackendService:
      baseConfig: default
    LexisNexisBackendService:
      baseConfig: default

resilience4j.ratelimiter:
  configs:
    default:
      limit-for-period: 4
      limit-refresh-period: 1s
      timeout-duration: 0s
      allow-health-indicator-to-fail: true
      subscribe-for-events: true
      event-consumer-buffer-size: 50
  instances:
    EwsBackendService:
      baseConfig: default
    LexisNexisBackendService:
      baseConfig: default

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 10
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 50
      slowCallDurationThreshold: 500
  instances:
    SimsBackendService:
      baseConfig: default
    LexisNexisBackendService:
      baseConfig: default    

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 100
  instances:
    AngBackendService:
      baseConfig: default
    LexisNexisBackendService:
      baseConfig: default      

backendService:
  baseUrl:  http://localhost:9090  
  path:
    aps:  /api/aps    
    ecpr: /api/ecpr
    ews:  /api/ews
    sims: /api/sims
    ang:  /api/ang
    lexisNexis: /api/lexisNexis
    
#apsUrl: http://localhost:9090/api/aps
apsUrl: http://localhost:9090/api/aps
ecprUrl: http://localhost:9090/api/ecpr
ewsUrl: http://localhost:9090/api/ews
simsUrl: http://localhost:9090/api/sims
angUrl: http://localhost:9090/api/ang
lexisNexisUrl: http://localhost:9090/api/lexisNexis

server:
  tomcat:
    accesslog:
      directory: /dev
      enabled: true
      prefix: stdout
      buffered: false
      suffix: ""
      file-date-format: ""

logging:
  level:
    root: INFO
    io:
      github: INFO
    okhttp3:  INFO
    com:
      demo: INFO   
      